version: '2.1'
services:
  banking:
    image: 'banking:latest'
    container_name: apihost
    restart: always
    build: .
    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8081:8080"




  postgres:
    image: 'postgres:latest'
    container_name: postgres
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: testtesttest

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5


#version: '3'
#
#services:
#  postgres:
#    image: 'postgres'
#    environment:
#      - POSTGRES_USER=postgres
#      - -POSTGRES_PASSWORD=testtesttest
#    ports:
#      '5432:5432'
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
#  banking:
#  build: .
#  ports:
#    - "9090:9090"
#  volumes:
#    - .:/banking

